steps:
# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/pubsub:$SHORT_SHA'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/pubsub:$SHORT_SHA'
  
# deploy container image to GKE
- name: "gcr.io/cloud-builders/pubsub"
  args:
  - run
  - --filename=kubernetes.yaml
  - --image=gcr.io/${PROJECT_ID}/pubsub:latest
  - --location=us-central1
  - --cluster=pubsub
# [END cloudbuild]
